const char* g_flat_shader_vert =
    "\n" "#version 420                                           "
    "\n" "layout(location = 0) in vec3 vert_pos;                 "
    "\n" "layout(location = 1) in vec4 vert_color;               "
    "\n" "layout(location = 2) in vec3 vert_tc;                  "
    "\n" "                                                       "
    "\n" "uniform mat4 projection;                               "
    "\n" "                                                       "
    "\n" "out vec4 frag_color;                                   "
    "\n" "out vec3 frag_tc;                                      "
    "\n" "out vec3 frag_norm;                                    "
    "\n" "                                                       "
    "\n" "void main(){                                           "
    "\n" "  gl_Position = projection * vec4(vert_pos, 1);        "
    "\n" "  frag_color = vert_color;                             "
    "\n" "  frag_tc = vert_tc;                                   "
    "\n" "}                                                      "
    "\n" ""
    "\n" "";

const char* g_flat_shader_frag =
    "\n" "#version 420                                              "
    "\n" "                                                          "
    "\n" "in vec4 frag_color;                                       "
    "\n" "in vec3 frag_tc;                                          "
    "\n" "in vec3 frag_norm;                                        "
    "\n" "                                                          "
    "\n" "uniform sampler2D texture_0;                              "
    "\n" "out vec4 out_color;                                       "
    "\n" "                                                          "
    "\n" "void main(){                                              "
    "\n" "  out_color = texture(texture_0, frag_tc.xy) * frag_color;"
    "\n" "}                                                         "
    "\n" "";

const char* g_text_shader_vert =
    "\n" "#version 420                                           "
    "\n" "layout(location = 0) in vec3 vert_pos;                 "
    "\n" "layout(location = 1) in vec4 vert_color;               "
    "\n" "layout(location = 2) in vec3 vert_tc;                  "
    "\n" "                                                       "
    "\n" "uniform mat4 projection;                               "
    "\n" "                                                       "
    "\n" "out vec4 frag_color;                                   "
    "\n" "out vec3 frag_tc;                                      "
    "\n" "out vec3 frag_norm;                                    "
    "\n" "                                                       "
    "\n" "void main(){                                           "
    "\n" "  gl_Position = projection * vec4(vert_pos, 1);        "
    "\n" "  frag_color = vert_color;                             "
    "\n" "  frag_tc = vert_tc;                                   "
    "\n" "}                                                      "
    "\n" ""
    "\n" "";

const char* g_text_shader_frag =
    "\n" "#version 420                                                "
    "\n" "                                                            "
    "\n" "in vec4 frag_color;                                         "
    "\n" "in vec3 frag_tc;                                            "
    "\n" "in vec3 frag_norm;                                          "
    "\n" "                                                            "
    "\n" "uniform sampler2DArray texture_0;                           "
    "\n" "out vec4 out_color;                                         "
    "\n" "                                                            "
    "\n" "void main(){                                                "
    "\n" "  out_color = texture(texture_0, frag_tc.xyz) * frag_color; "
    "\n" "  if(out_color.a == 0)                                      "
    "\n" "     discard;                                               "
    "\n" "}                                                           "
    "\n" "";
