FROM python:3.12-slim

# Configure Poetry environment
ENV POETRY_HOME="/opt/poetry"
ENV PATH="/root/.local/bin:$PATH"
ENV POETRY_VIRTUALENVS_CREATE=false


# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget xz-utils && rm -rf /var/lib/apt/lists/*
      
RUN wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl-shared.tar.xz
RUN tar -xvf ffmpeg-master-latest-linux64-gpl-shared.tar.xz
RUN mv ffmpeg-master-latest-linux64-gpl-shared/bin/ffmpeg /usr/local/bin/ 
RUN mv ffmpeg-master-latest-linux64-gpl-shared/bin/ffprobe /usr/local/bin/

# Install Poetry
RUN pip install poetry

# Copy backend dependency files and install Python dependencies
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --no-interaction --no-ansi

# Copy the backend source code
COPY smart_canvas /smart_canvas
COPY models /models
COPY web /web


# Set Flask environment variables
ENV FLASK_APP=web
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
ENV PYTHONUNBUFFERED=1

# Expose the Flask port
EXPOSE 5000

# Start Flask server
CMD ["poetry", "run", "flask", "run", "--host=0.0.0.0", "--debug"]