readonly CONTAINER_REMOVE_ENABLED="TRUE"
readonly IMAGE_REMOVE_ENABLED="TRUE"

readonly UPGRADE_PACKAGES="FALSE"

readonly NODEJS_VERSION="24.10.0"

# See variant options from constants.sh
readonly FRONTEND_BUILD_VARIANT="${BUILD_VARIANT_CONSENT_ON}"

# A new value for endpoint path can conveniently be generated by using
# KeePassXC.
# https://keepassxc.org/
# Tools -> Password Generator -> Passphrase
#
# The value of this variable determines the path that is used for serving the
# frontend. For example with the value 'smartcanvas', the frontend can be
# accessed at `https://<VIRTUAL_MACHINE_DNS_NAME>/smartcanvas`.
#
# Please do not push a commit that contains a value for BACKEND_APP_ENDPOINT as
# the value is intended to be kept secret. This is a duct tape solution to make
# unauthorized access to application more difficult.
readonly BACKEND_APP_ENDPOINT=""

# https://docs.csc.fi/cloud/pouta/additional-services/#custom-dns-name
#
# It is not recommended to use predefined fip-XXX... DNS names in
# production.
readonly VIRTUAL_MACHINE_DNS_NAME=""
